### ISSUE TITLE
NAMESILO_HOST_REGEX does not match all expected subdomains

### ISSUE THREAD

**Issue by IcerOut** [aderesh/namesiloddns#2]
Using a value of `$^|\*` for NAMESILO_HOST_REGEX does not work as expected.
I have 2 hosts on the domain I'm trying to update, a wildcard record (`*`) and a blank one ("")
I've checked the regex above using regex101.com and it should work as expected (matches both values and nothing else), so the pattern should be OK.

However, when my IP changed, only the blank DNS record ("") was updated, and the wildcard one kept the old value.
@aderesh Could you please look into this when you have the time?

**Comment by aderesh** [comment]
@IcerOut , sorry for the long reply - haven't noticed this issue before. First thing first "Host" in terms of namesilo is "blog.example.com" and not just "blog" - I'll review API and make it a more clear in docs. Therefore, using .NET regex:
<img width="874" alt="image" src="https://github.com/aderesh/namesiloddns/assets/2285614/16d4bb51-acdb-4d4f-9dd3-f0bafa15e1ff">

To achieve what you want, I'd use something like this
<img width="549" alt="image" src="https://github.com/aderesh/namesiloddns/assets/2285614/2fafaaa0-756e-433f-8986-02498e2de688">
where "example.org" is your NAMESILO_DOMAIN
